name: deploy docs to gitee & gitlab

on:
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2         
    - name: Configure Private Key
      env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
          SSH_PUB_KEY: ${{secrets.GITEE_RSA_PUB_KEY}}
      run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          echo "$SSH_PUB_KEY" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
        
    - name: Push docs to Gitlab
      env: 
        PROJ_PATH: ${{github.workspace}} 
        GIT_LAB: git@gitlab.com:wsj0051/wsj0051.gitlab.io.git
      run: |
        cd ${PROJ_PATH}/
        mkdir -p ~/wsj0051
        rm -rf .github/ .git/
        git clone ${GIT_LAB} ~/wsj0051/docs
        rm -rf  ~/wsj0051/docs/public/*
        cp -r ./*  ~/wsj0051/docs/public
        cd ~/wsj0051/docs/
        git config --global user.email "wsj0051@163.com" 
        git config --global user.name "wsj0051"   
        git add .
        git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
        git push --force --quiet origin master 
